### ISSUE TITLE
Create Project Skeleton

### ISSUE THREAD

**Issue by ajfrank** [DiAJVince/graceshopper#3]

**Comment by Riv-Con** [comment]
This is going to consist of the following:

1. In the master branch I am simply going to create the folder structure and a few representative empty files for our application.  This assumes a React-Redux app equivalent to one we would do for a weekend project.

2. I am then going to create a branch from that folder structure called "template_VR".  This branch will be a working template with all the files necessary to show that the application is wired correctly.  It will be a baseline template that we can work from.

3.  Once I am finished with writing and testing my branch, I will contact my team-mates so that we can decide whether to merge it with the master branch.
